// lib/models.ts
export const MODELS = [
  {
<<<<<<< HEAD
    id: 'meta-llama/llama-3.1-405b-instruct', // ID
    name: 'LLaMA 3.1', // MODEL NAME
    provider: 'huggingface', // COMPAMY
    premium: false, // IF INPUT/output PRICE more then 2$ 
    experimental: false, // likha hoga
    onlyBYK: false, // if too expensive
    supports: ['image', 'document', 'reasoning' ],
=======
    id: 'meta-llama/llama-3.1-405b-instruct',
    name: 'LLaMA 3.1',
    provider: 'meta',
    premium: true,
    experimental: false,
    onlyBYK: false,
    supports: ['text', 'reasoning'],
>>>>>>> bbe58265d5d3efb778a809243fb1cf4fd9a8f58c
  },
  {
    id: 'anthropic/claude-3-opus',
    name: 'Claude 3 Opus',
    provider: 'anthropic',
    premium: true,
    experimental: false,
    onlyBYK: false,
    supports: ['text', 'image', 'document', 'reasoning'],
  },
  {
    id: 'google/gemini-pro',
    name: 'Gemini Pro',
    provider: 'google',
    premium: false,
    experimental: false,
    onlyBYK: false,
    supports: ['text', 'reasoning'],
  },
  {
    id: 'mistralai/mistral-large',
    name: 'Mistral Large',
    provider: 'mistral',
    premium: true,
    experimental: false,
    onlyBYK: false,
    supports: ['text', 'reasoning'],
  },
  {
    id: 'deepseek/deepseek-coder',
    name: 'DeepSeek Coder',
    provider: 'deepseek',
    premium: false,
    experimental: false,
    onlyBYK: false,
    supports: ['text', 'document', 'reasoning'],
  },
  {
    id: 'anthropic/claude-3-sonnet',
    name: 'Claude 3 Sonnet',
    provider: 'anthropic',
    premium: true,
    experimental: false,
    onlyBYK: false,
    supports: ['text', 'image', 'document', 'reasoning'],
  },
  {
    id: 'meta-llama/llama-2-70b-chat',
    name: 'Llama 2 70B',
    provider: 'meta',
    premium: false,
    experimental: false,
    onlyBYK: false,
    supports: ['text', 'reasoning'],
  },
  {
    id: 'google/gemini-pro-vision',
    name: 'Gemini Pro Vision',
    provider: 'google',
    premium: false,
    experimental: false,
    onlyBYK: false,
    supports: ['text', 'image', 'reasoning'],
  },
  {
    id: 'mistralai/mixtral-8x7b',
    name: 'Mixtral 8x7B',
    provider: 'mistral',
    premium: false,
    experimental: false,
    onlyBYK: false,
    supports: ['text', 'reasoning'],
  },
  {
    id: 'perplexity/pplx-70b-online',
    name: 'PPLX 70B Online',
    provider: 'perplexity',
    premium: true,
    experimental: false,
    onlyBYK: false,
    supports: ['text', 'web_search', 'reasoning'],
  },
  {
    id: 'anthropic/claude-2.1',
    name: 'Claude 2.1',
    provider: 'anthropic',
    premium: true,
    experimental: false,
    onlyBYK: false,
    supports: ['text', 'document', 'reasoning'],
  },
  {
    id: 'openai/gpt-4-vision',
    name: 'GPT-4 Vision',
    provider: 'openai',
    premium: true,
    experimental: false,
    onlyBYK: false,
    supports: ['text', 'image', 'reasoning'],
  },
  {
    id: 'deepseek/deepseek-math',
    name: 'DeepSeek Math',
    provider: 'deepseek',
    premium: false,
    experimental: true,
    onlyBYK: false,
    supports: ['text', 'reasoning'],
  },
  {
    id: 'meta-llama/llama-2-13b-chat:free',
    name: 'Llama 2 13B Free',
    provider: 'meta',
    premium: false,
    experimental: false,
    onlyBYK: false,
    supports: ['text'],
  },
  {
    id: 'mistralai/mistral-7b:free',
    name: 'Mistral 7B Free',
    provider: 'mistral',
    premium: false,
    experimental: false,
    onlyBYK: false,
    supports: ['text'],
  }
];
